version: 1.0.{build}

image:
- Visual Studio 2013
- Visual Studio 2015

configuration: Release

platform: Any CPU

build_script:
- cmd: .\build.cmd Build

test:
  assemblies:
  - .\build\*.UnitTests.dll
  - .\build\*.ContractTests.dll

notifications:
- provider: Email
  to:
  - this@parthopdas.com
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true
